//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InicioSesion
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public long IdUsuario { get; set; }
        public string Usuario1 { get; set; }
        public string Contrasenia { get; set; }
        public System.DateTime UltimoAcceso { get; set; }
    }
}
